// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.3
// source: vtickets.proto

package vtickets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// represents integer range [lower, upper)
type VTicketRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lower         int64                  `protobuf:"varint,1,opt,name=lower,proto3" json:"lower,omitempty"`
	Upper         int64                  `protobuf:"varint,2,opt,name=upper,proto3" json:"upper,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VTicketRange) Reset() {
	*x = VTicketRange{}
	mi := &file_vtickets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VTicketRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTicketRange) ProtoMessage() {}

func (x *VTicketRange) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTicketRange.ProtoReflect.Descriptor instead.
func (*VTicketRange) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{0}
}

func (x *VTicketRange) GetLower() int64 {
	if x != nil {
		return x.Lower
	}
	return 0
}

func (x *VTicketRange) GetUpper() int64 {
	if x != nil {
		return x.Upper
	}
	return 0
}

type VTicketRanges struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranges        []*VTicketRange        `protobuf:"bytes,1,rep,name=ranges,proto3" json:"ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VTicketRanges) Reset() {
	*x = VTicketRanges{}
	mi := &file_vtickets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VTicketRanges) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTicketRanges) ProtoMessage() {}

func (x *VTicketRanges) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTicketRanges.ProtoReflect.Descriptor instead.
func (*VTicketRanges) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{1}
}

func (x *VTicketRanges) GetRanges() []*VTicketRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

// pulls a batch of tickets from the tickets server.
// the response may contain ranges larger than `minimumTickets`
// if the upstream service has determined the requested batch
// sizes are too small for the current throughput
type GetVTicketRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Keyspace       string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table          string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	MinimumTickets int32                  `protobuf:"varint,3,opt,name=minimumTickets,proto3" json:"minimumTickets,omitempty"`
	BigIntColumn   bool                   `protobuf:"varint,4,opt,name=bigIntColumn,proto3" json:"bigIntColumn,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVTicketRequest) Reset() {
	*x = GetVTicketRequest{}
	mi := &file_vtickets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVTicketRequest) ProtoMessage() {}

func (x *GetVTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVTicketRequest.ProtoReflect.Descriptor instead.
func (*GetVTicketRequest) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{2}
}

func (x *GetVTicketRequest) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *GetVTicketRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *GetVTicketRequest) GetMinimumTickets() int32 {
	if x != nil {
		return x.MinimumTickets
	}
	return 0
}

func (x *GetVTicketRequest) GetBigIntColumn() bool {
	if x != nil {
		return x.BigIntColumn
	}
	return false
}

type GetVTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyspace      string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	VticketRanges *VTicketRanges         `protobuf:"bytes,3,opt,name=vticket_ranges,json=vticketRanges,proto3" json:"vticket_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVTicketResponse) Reset() {
	*x = GetVTicketResponse{}
	mi := &file_vtickets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVTicketResponse) ProtoMessage() {}

func (x *GetVTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVTicketResponse.ProtoReflect.Descriptor instead.
func (*GetVTicketResponse) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{3}
}

func (x *GetVTicketResponse) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *GetVTicketResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *GetVTicketResponse) GetVticketRanges() *VTicketRanges {
	if x != nil {
		return x.VticketRanges
	}
	return nil
}

// read-only view of available tickets on the tickets server
type ViewVTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyspace      string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewVTicketsRequest) Reset() {
	*x = ViewVTicketsRequest{}
	mi := &file_vtickets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewVTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewVTicketsRequest) ProtoMessage() {}

func (x *ViewVTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewVTicketsRequest.ProtoReflect.Descriptor instead.
func (*ViewVTicketsRequest) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{4}
}

func (x *ViewVTicketsRequest) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *ViewVTicketsRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

type ViewVTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyspace      string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	VticketRanges *VTicketRanges         `protobuf:"bytes,3,opt,name=vticket_ranges,json=vticketRanges,proto3" json:"vticket_ranges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewVTicketsResponse) Reset() {
	*x = ViewVTicketsResponse{}
	mi := &file_vtickets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewVTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewVTicketsResponse) ProtoMessage() {}

func (x *ViewVTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewVTicketsResponse.ProtoReflect.Descriptor instead.
func (*ViewVTicketsResponse) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{5}
}

func (x *ViewVTicketsResponse) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *ViewVTicketsResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ViewVTicketsResponse) GetVticketRanges() *VTicketRanges {
	if x != nil {
		return x.VticketRanges
	}
	return nil
}

// healthcheck
type HealthcheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckRequest) Reset() {
	*x = HealthcheckRequest{}
	mi := &file_vtickets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckRequest) ProtoMessage() {}

func (x *HealthcheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckRequest.ProtoReflect.Descriptor instead.
func (*HealthcheckRequest) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{6}
}

type HealthcheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthcheckResponse) Reset() {
	*x = HealthcheckResponse{}
	mi := &file_vtickets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthcheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthcheckResponse) ProtoMessage() {}

func (x *HealthcheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthcheckResponse.ProtoReflect.Descriptor instead.
func (*HealthcheckResponse) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{7}
}

// get all stored VTickets
type ViewAllVTicketsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAllVTicketsRequest) Reset() {
	*x = ViewAllVTicketsRequest{}
	mi := &file_vtickets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAllVTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAllVTicketsRequest) ProtoMessage() {}

func (x *ViewAllVTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAllVTicketsRequest.ProtoReflect.Descriptor instead.
func (*ViewAllVTicketsRequest) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{8}
}

type ViewAllVTicketsResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Vtickets      []*ViewVTicketsResponse `protobuf:"bytes,1,rep,name=vtickets,proto3" json:"vtickets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewAllVTicketsResponse) Reset() {
	*x = ViewAllVTicketsResponse{}
	mi := &file_vtickets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewAllVTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewAllVTicketsResponse) ProtoMessage() {}

func (x *ViewAllVTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewAllVTicketsResponse.ProtoReflect.Descriptor instead.
func (*ViewAllVTicketsResponse) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{9}
}

func (x *ViewAllVTicketsResponse) GetVtickets() []*ViewVTicketsResponse {
	if x != nil {
		return x.Vtickets
	}
	return nil
}

// creates or updates a VTicket to a new value
type SetGlobalVTicketRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Keyspace     string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table        string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	NextTicketId int64                  `protobuf:"varint,3,opt,name=nextTicketId,proto3" json:"nextTicketId,omitempty"`
	// by default, we'll disallow setting the ticket id lower than what has been issued
	AllowDecrease bool `protobuf:"varint,4,opt,name=allowDecrease,proto3" json:"allowDecrease,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalVTicketRequest) Reset() {
	*x = SetGlobalVTicketRequest{}
	mi := &file_vtickets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalVTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalVTicketRequest) ProtoMessage() {}

func (x *SetGlobalVTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalVTicketRequest.ProtoReflect.Descriptor instead.
func (*SetGlobalVTicketRequest) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{10}
}

func (x *SetGlobalVTicketRequest) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *SetGlobalVTicketRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SetGlobalVTicketRequest) GetNextTicketId() int64 {
	if x != nil {
		return x.NextTicketId
	}
	return 0
}

func (x *SetGlobalVTicketRequest) GetAllowDecrease() bool {
	if x != nil {
		return x.AllowDecrease
	}
	return false
}

type SetGlobalVTicketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyspace      string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	NextTicketId  int64                  `protobuf:"varint,3,opt,name=nextTicketId,proto3" json:"nextTicketId,omitempty"`
	Successful    bool                   `protobuf:"varint,4,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetGlobalVTicketResponse) Reset() {
	*x = SetGlobalVTicketResponse{}
	mi := &file_vtickets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetGlobalVTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGlobalVTicketResponse) ProtoMessage() {}

func (x *SetGlobalVTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGlobalVTicketResponse.ProtoReflect.Descriptor instead.
func (*SetGlobalVTicketResponse) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{11}
}

func (x *SetGlobalVTicketResponse) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *SetGlobalVTicketResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *SetGlobalVTicketResponse) GetNextTicketId() int64 {
	if x != nil {
		return x.NextTicketId
	}
	return 0
}

func (x *SetGlobalVTicketResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

// clear the tickets available on a Hublet
type ClearHubletVTicketsRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Keyspace string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table    string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	// optional: a specific range to remove. lower bound must be <= the persisted lower bound
	// so that the persisted ranges do not fragment
	VticketRange  *VTicketRange `protobuf:"bytes,3,opt,name=vticketRange,proto3" json:"vticketRange,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHubletVTicketsRequest) Reset() {
	*x = ClearHubletVTicketsRequest{}
	mi := &file_vtickets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHubletVTicketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHubletVTicketsRequest) ProtoMessage() {}

func (x *ClearHubletVTicketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHubletVTicketsRequest.ProtoReflect.Descriptor instead.
func (*ClearHubletVTicketsRequest) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{12}
}

func (x *ClearHubletVTicketsRequest) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *ClearHubletVTicketsRequest) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ClearHubletVTicketsRequest) GetVticketRange() *VTicketRange {
	if x != nil {
		return x.VticketRange
	}
	return nil
}

type ClearHubletVTicketsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keyspace      string                 `protobuf:"bytes,1,opt,name=keyspace,proto3" json:"keyspace,omitempty"`
	Table         string                 `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	Successful    bool                   `protobuf:"varint,3,opt,name=successful,proto3" json:"successful,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearHubletVTicketsResponse) Reset() {
	*x = ClearHubletVTicketsResponse{}
	mi := &file_vtickets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearHubletVTicketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearHubletVTicketsResponse) ProtoMessage() {}

func (x *ClearHubletVTicketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_vtickets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearHubletVTicketsResponse.ProtoReflect.Descriptor instead.
func (*ClearHubletVTicketsResponse) Descriptor() ([]byte, []int) {
	return file_vtickets_proto_rawDescGZIP(), []int{13}
}

func (x *ClearHubletVTicketsResponse) GetKeyspace() string {
	if x != nil {
		return x.Keyspace
	}
	return ""
}

func (x *ClearHubletVTicketsResponse) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ClearHubletVTicketsResponse) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

var File_vtickets_proto protoreflect.FileDescriptor

const file_vtickets_proto_rawDesc = "" +
	"\n" +
	"\x0evtickets.proto\x12\x10hubspot.vtickets\":\n" +
	"\fVTicketRange\x12\x14\n" +
	"\x05lower\x18\x01 \x01(\x03R\x05lower\x12\x14\n" +
	"\x05upper\x18\x02 \x01(\x03R\x05upper\"G\n" +
	"\rVTicketRanges\x126\n" +
	"\x06ranges\x18\x01 \x03(\v2\x1e.hubspot.vtickets.VTicketRangeR\x06ranges\"\x91\x01\n" +
	"\x11GetVTicketRequest\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12&\n" +
	"\x0eminimumTickets\x18\x03 \x01(\x05R\x0eminimumTickets\x12\"\n" +
	"\fbigIntColumn\x18\x04 \x01(\bR\fbigIntColumn\"\x8e\x01\n" +
	"\x12GetVTicketResponse\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12F\n" +
	"\x0evticket_ranges\x18\x03 \x01(\v2\x1f.hubspot.vtickets.VTicketRangesR\rvticketRanges\"G\n" +
	"\x13ViewVTicketsRequest\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\"\x90\x01\n" +
	"\x14ViewVTicketsResponse\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12F\n" +
	"\x0evticket_ranges\x18\x03 \x01(\v2\x1f.hubspot.vtickets.VTicketRangesR\rvticketRanges\"\x14\n" +
	"\x12HealthcheckRequest\"\x15\n" +
	"\x13HealthcheckResponse\"\x18\n" +
	"\x16ViewAllVTicketsRequest\"]\n" +
	"\x17ViewAllVTicketsResponse\x12B\n" +
	"\bvtickets\x18\x01 \x03(\v2&.hubspot.vtickets.ViewVTicketsResponseR\bvtickets\"\x95\x01\n" +
	"\x17SetGlobalVTicketRequest\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\"\n" +
	"\fnextTicketId\x18\x03 \x01(\x03R\fnextTicketId\x12$\n" +
	"\rallowDecrease\x18\x04 \x01(\bR\rallowDecrease\"\x90\x01\n" +
	"\x18SetGlobalVTicketResponse\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\"\n" +
	"\fnextTicketId\x18\x03 \x01(\x03R\fnextTicketId\x12\x1e\n" +
	"\n" +
	"successful\x18\x04 \x01(\bR\n" +
	"successful\"\x92\x01\n" +
	"\x1aClearHubletVTicketsRequest\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12B\n" +
	"\fvticketRange\x18\x03 \x01(\v2\x1e.hubspot.vtickets.VTicketRangeR\fvticketRange\"o\n" +
	"\x1bClearHubletVTicketsResponse\x12\x1a\n" +
	"\bkeyspace\x18\x01 \x01(\tR\bkeyspace\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x12\x1e\n" +
	"\n" +
	"successful\x18\x03 \x01(\bR\n" +
	"successfulBS\n" +
	"\x1acom.hubspot.vtickets.protoB\fVTicketProtoP\x01Z%vitess.io/vitess/go/vt/proto/vticketsb\x06proto3"

var (
	file_vtickets_proto_rawDescOnce sync.Once
	file_vtickets_proto_rawDescData []byte
)

func file_vtickets_proto_rawDescGZIP() []byte {
	file_vtickets_proto_rawDescOnce.Do(func() {
		file_vtickets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vtickets_proto_rawDesc), len(file_vtickets_proto_rawDesc)))
	})
	return file_vtickets_proto_rawDescData
}

var file_vtickets_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_vtickets_proto_goTypes = []any{
	(*VTicketRange)(nil),                // 0: hubspot.vtickets.VTicketRange
	(*VTicketRanges)(nil),               // 1: hubspot.vtickets.VTicketRanges
	(*GetVTicketRequest)(nil),           // 2: hubspot.vtickets.GetVTicketRequest
	(*GetVTicketResponse)(nil),          // 3: hubspot.vtickets.GetVTicketResponse
	(*ViewVTicketsRequest)(nil),         // 4: hubspot.vtickets.ViewVTicketsRequest
	(*ViewVTicketsResponse)(nil),        // 5: hubspot.vtickets.ViewVTicketsResponse
	(*HealthcheckRequest)(nil),          // 6: hubspot.vtickets.HealthcheckRequest
	(*HealthcheckResponse)(nil),         // 7: hubspot.vtickets.HealthcheckResponse
	(*ViewAllVTicketsRequest)(nil),      // 8: hubspot.vtickets.ViewAllVTicketsRequest
	(*ViewAllVTicketsResponse)(nil),     // 9: hubspot.vtickets.ViewAllVTicketsResponse
	(*SetGlobalVTicketRequest)(nil),     // 10: hubspot.vtickets.SetGlobalVTicketRequest
	(*SetGlobalVTicketResponse)(nil),    // 11: hubspot.vtickets.SetGlobalVTicketResponse
	(*ClearHubletVTicketsRequest)(nil),  // 12: hubspot.vtickets.ClearHubletVTicketsRequest
	(*ClearHubletVTicketsResponse)(nil), // 13: hubspot.vtickets.ClearHubletVTicketsResponse
}
var file_vtickets_proto_depIdxs = []int32{
	0, // 0: hubspot.vtickets.VTicketRanges.ranges:type_name -> hubspot.vtickets.VTicketRange
	1, // 1: hubspot.vtickets.GetVTicketResponse.vticket_ranges:type_name -> hubspot.vtickets.VTicketRanges
	1, // 2: hubspot.vtickets.ViewVTicketsResponse.vticket_ranges:type_name -> hubspot.vtickets.VTicketRanges
	5, // 3: hubspot.vtickets.ViewAllVTicketsResponse.vtickets:type_name -> hubspot.vtickets.ViewVTicketsResponse
	0, // 4: hubspot.vtickets.ClearHubletVTicketsRequest.vticketRange:type_name -> hubspot.vtickets.VTicketRange
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_vtickets_proto_init() }
func file_vtickets_proto_init() {
	if File_vtickets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vtickets_proto_rawDesc), len(file_vtickets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_vtickets_proto_goTypes,
		DependencyIndexes: file_vtickets_proto_depIdxs,
		MessageInfos:      file_vtickets_proto_msgTypes,
	}.Build()
	File_vtickets_proto = out.File
	file_vtickets_proto_goTypes = nil
	file_vtickets_proto_depIdxs = nil
}
