// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.3
// source: vticketsservice.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
	vtickets "vitess.io/vitess/go/vt/proto/vtickets"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_vticketsservice_proto protoreflect.FileDescriptor

const file_vticketsservice_proto_rawDesc = "" +
	"\n" +
	"\x15vticketsservice.proto\x12\x15hubspot.vtickets.grpc\x1a\x0evtickets.proto2\x8b\x03\n" +
	"\x0eVTicketService\x12R\n" +
	"\x03Get\x12#.hubspot.vtickets.GetVTicketRequest\x1a$.hubspot.vtickets.GetVTicketResponse\"\x00\x12^\n" +
	"\vViewTickets\x12%.hubspot.vtickets.ViewVTicketsRequest\x1a&.hubspot.vtickets.ViewVTicketsResponse\"\x00\x12g\n" +
	"\x0eViewAllTickets\x12(.hubspot.vtickets.ViewAllVTicketsRequest\x1a).hubspot.vtickets.ViewAllVTicketsResponse\"\x00\x12\\\n" +
	"\vHealthcheck\x12$.hubspot.vtickets.HealthcheckRequest\x1a%.hubspot.vtickets.HealthcheckResponse\"\x002|\n" +
	"\x14GlobalVTicketService\x12d\n" +
	"\tSetTicket\x12).hubspot.vtickets.SetGlobalVTicketRequest\x1a*.hubspot.vtickets.SetGlobalVTicketResponse\"\x002\x84\x01\n" +
	"\x14HubletVTicketService\x12l\n" +
	"\vClearTicket\x12,.hubspot.vtickets.ClearHubletVTicketsRequest\x1a-.hubspot.vtickets.ClearHubletVTicketsResponse\"\x00BY\n" +
	"\x1fcom.hubspot.vtickets.proto.grpcB\n" +
	"VTicketRpcZ*vitess.io/vitess/go/vt/proto/vtickets/grpcb\x06proto3"

var file_vticketsservice_proto_goTypes = []any{
	(*vtickets.GetVTicketRequest)(nil),           // 0: hubspot.vtickets.GetVTicketRequest
	(*vtickets.ViewVTicketsRequest)(nil),         // 1: hubspot.vtickets.ViewVTicketsRequest
	(*vtickets.ViewAllVTicketsRequest)(nil),      // 2: hubspot.vtickets.ViewAllVTicketsRequest
	(*vtickets.HealthcheckRequest)(nil),          // 3: hubspot.vtickets.HealthcheckRequest
	(*vtickets.SetGlobalVTicketRequest)(nil),     // 4: hubspot.vtickets.SetGlobalVTicketRequest
	(*vtickets.ClearHubletVTicketsRequest)(nil),  // 5: hubspot.vtickets.ClearHubletVTicketsRequest
	(*vtickets.GetVTicketResponse)(nil),          // 6: hubspot.vtickets.GetVTicketResponse
	(*vtickets.ViewVTicketsResponse)(nil),        // 7: hubspot.vtickets.ViewVTicketsResponse
	(*vtickets.ViewAllVTicketsResponse)(nil),     // 8: hubspot.vtickets.ViewAllVTicketsResponse
	(*vtickets.HealthcheckResponse)(nil),         // 9: hubspot.vtickets.HealthcheckResponse
	(*vtickets.SetGlobalVTicketResponse)(nil),    // 10: hubspot.vtickets.SetGlobalVTicketResponse
	(*vtickets.ClearHubletVTicketsResponse)(nil), // 11: hubspot.vtickets.ClearHubletVTicketsResponse
}
var file_vticketsservice_proto_depIdxs = []int32{
	0,  // 0: hubspot.vtickets.grpc.VTicketService.Get:input_type -> hubspot.vtickets.GetVTicketRequest
	1,  // 1: hubspot.vtickets.grpc.VTicketService.ViewTickets:input_type -> hubspot.vtickets.ViewVTicketsRequest
	2,  // 2: hubspot.vtickets.grpc.VTicketService.ViewAllTickets:input_type -> hubspot.vtickets.ViewAllVTicketsRequest
	3,  // 3: hubspot.vtickets.grpc.VTicketService.Healthcheck:input_type -> hubspot.vtickets.HealthcheckRequest
	4,  // 4: hubspot.vtickets.grpc.GlobalVTicketService.SetTicket:input_type -> hubspot.vtickets.SetGlobalVTicketRequest
	5,  // 5: hubspot.vtickets.grpc.HubletVTicketService.ClearTicket:input_type -> hubspot.vtickets.ClearHubletVTicketsRequest
	6,  // 6: hubspot.vtickets.grpc.VTicketService.Get:output_type -> hubspot.vtickets.GetVTicketResponse
	7,  // 7: hubspot.vtickets.grpc.VTicketService.ViewTickets:output_type -> hubspot.vtickets.ViewVTicketsResponse
	8,  // 8: hubspot.vtickets.grpc.VTicketService.ViewAllTickets:output_type -> hubspot.vtickets.ViewAllVTicketsResponse
	9,  // 9: hubspot.vtickets.grpc.VTicketService.Healthcheck:output_type -> hubspot.vtickets.HealthcheckResponse
	10, // 10: hubspot.vtickets.grpc.GlobalVTicketService.SetTicket:output_type -> hubspot.vtickets.SetGlobalVTicketResponse
	11, // 11: hubspot.vtickets.grpc.HubletVTicketService.ClearTicket:output_type -> hubspot.vtickets.ClearHubletVTicketsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_vticketsservice_proto_init() }
func file_vticketsservice_proto_init() {
	if File_vticketsservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vticketsservice_proto_rawDesc), len(file_vticketsservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_vticketsservice_proto_goTypes,
		DependencyIndexes: file_vticketsservice_proto_depIdxs,
	}.Build()
	File_vticketsservice_proto = out.File
	file_vticketsservice_proto_goTypes = nil
	file_vticketsservice_proto_depIdxs = nil
}
