// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.3
// source: vticketsservice.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	vtickets "vitess.io/vitess/go/vt/proto/vtickets"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VTicketServiceClient is the client API for VTicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VTicketServiceClient interface {
	// fetches and persists a batch of tickets
	Get(ctx context.Context, in *vtickets.GetVTicketRequest, opts ...grpc.CallOption) (*vtickets.GetVTicketResponse, error)
	// read-only call to view the current ranges persisted on the service
	ViewTickets(ctx context.Context, in *vtickets.ViewVTicketsRequest, opts ...grpc.CallOption) (*vtickets.ViewVTicketsResponse, error)
	// read-only call to view all of the current ranges persisted on the service
	ViewAllTickets(ctx context.Context, in *vtickets.ViewAllVTicketsRequest, opts ...grpc.CallOption) (*vtickets.ViewAllVTicketsResponse, error)
	// for Kube readiness / liveness checks
	Healthcheck(ctx context.Context, in *vtickets.HealthcheckRequest, opts ...grpc.CallOption) (*vtickets.HealthcheckResponse, error)
}

type vTicketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVTicketServiceClient(cc grpc.ClientConnInterface) VTicketServiceClient {
	return &vTicketServiceClient{cc}
}

func (c *vTicketServiceClient) Get(ctx context.Context, in *vtickets.GetVTicketRequest, opts ...grpc.CallOption) (*vtickets.GetVTicketResponse, error) {
	out := new(vtickets.GetVTicketResponse)
	err := c.cc.Invoke(ctx, "/hubspot.vtickets.grpc.VTicketService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTicketServiceClient) ViewTickets(ctx context.Context, in *vtickets.ViewVTicketsRequest, opts ...grpc.CallOption) (*vtickets.ViewVTicketsResponse, error) {
	out := new(vtickets.ViewVTicketsResponse)
	err := c.cc.Invoke(ctx, "/hubspot.vtickets.grpc.VTicketService/ViewTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTicketServiceClient) ViewAllTickets(ctx context.Context, in *vtickets.ViewAllVTicketsRequest, opts ...grpc.CallOption) (*vtickets.ViewAllVTicketsResponse, error) {
	out := new(vtickets.ViewAllVTicketsResponse)
	err := c.cc.Invoke(ctx, "/hubspot.vtickets.grpc.VTicketService/ViewAllTickets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vTicketServiceClient) Healthcheck(ctx context.Context, in *vtickets.HealthcheckRequest, opts ...grpc.CallOption) (*vtickets.HealthcheckResponse, error) {
	out := new(vtickets.HealthcheckResponse)
	err := c.cc.Invoke(ctx, "/hubspot.vtickets.grpc.VTicketService/Healthcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VTicketServiceServer is the server API for VTicketService service.
// All implementations must embed UnimplementedVTicketServiceServer
// for forward compatibility
type VTicketServiceServer interface {
	// fetches and persists a batch of tickets
	Get(context.Context, *vtickets.GetVTicketRequest) (*vtickets.GetVTicketResponse, error)
	// read-only call to view the current ranges persisted on the service
	ViewTickets(context.Context, *vtickets.ViewVTicketsRequest) (*vtickets.ViewVTicketsResponse, error)
	// read-only call to view all of the current ranges persisted on the service
	ViewAllTickets(context.Context, *vtickets.ViewAllVTicketsRequest) (*vtickets.ViewAllVTicketsResponse, error)
	// for Kube readiness / liveness checks
	Healthcheck(context.Context, *vtickets.HealthcheckRequest) (*vtickets.HealthcheckResponse, error)
	mustEmbedUnimplementedVTicketServiceServer()
}

// UnimplementedVTicketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVTicketServiceServer struct {
}

func (UnimplementedVTicketServiceServer) Get(context.Context, *vtickets.GetVTicketRequest) (*vtickets.GetVTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVTicketServiceServer) ViewTickets(context.Context, *vtickets.ViewVTicketsRequest) (*vtickets.ViewVTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewTickets not implemented")
}
func (UnimplementedVTicketServiceServer) ViewAllTickets(context.Context, *vtickets.ViewAllVTicketsRequest) (*vtickets.ViewAllVTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewAllTickets not implemented")
}
func (UnimplementedVTicketServiceServer) Healthcheck(context.Context, *vtickets.HealthcheckRequest) (*vtickets.HealthcheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Healthcheck not implemented")
}
func (UnimplementedVTicketServiceServer) mustEmbedUnimplementedVTicketServiceServer() {}

// UnsafeVTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VTicketServiceServer will
// result in compilation errors.
type UnsafeVTicketServiceServer interface {
	mustEmbedUnimplementedVTicketServiceServer()
}

func RegisterVTicketServiceServer(s grpc.ServiceRegistrar, srv VTicketServiceServer) {
	s.RegisterService(&VTicketService_ServiceDesc, srv)
}

func _VTicketService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vtickets.GetVTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTicketServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubspot.vtickets.grpc.VTicketService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTicketServiceServer).Get(ctx, req.(*vtickets.GetVTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTicketService_ViewTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vtickets.ViewVTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTicketServiceServer).ViewTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubspot.vtickets.grpc.VTicketService/ViewTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTicketServiceServer).ViewTickets(ctx, req.(*vtickets.ViewVTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTicketService_ViewAllTickets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vtickets.ViewAllVTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTicketServiceServer).ViewAllTickets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubspot.vtickets.grpc.VTicketService/ViewAllTickets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTicketServiceServer).ViewAllTickets(ctx, req.(*vtickets.ViewAllVTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VTicketService_Healthcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vtickets.HealthcheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VTicketServiceServer).Healthcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubspot.vtickets.grpc.VTicketService/Healthcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VTicketServiceServer).Healthcheck(ctx, req.(*vtickets.HealthcheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VTicketService_ServiceDesc is the grpc.ServiceDesc for VTicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VTicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hubspot.vtickets.grpc.VTicketService",
	HandlerType: (*VTicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _VTicketService_Get_Handler,
		},
		{
			MethodName: "ViewTickets",
			Handler:    _VTicketService_ViewTickets_Handler,
		},
		{
			MethodName: "ViewAllTickets",
			Handler:    _VTicketService_ViewAllTickets_Handler,
		},
		{
			MethodName: "Healthcheck",
			Handler:    _VTicketService_Healthcheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vticketsservice.proto",
}

// GlobalVTicketServiceClient is the client API for GlobalVTicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GlobalVTicketServiceClient interface {
	// creates or updates a ticket to start from a specific value
	SetTicket(ctx context.Context, in *vtickets.SetGlobalVTicketRequest, opts ...grpc.CallOption) (*vtickets.SetGlobalVTicketResponse, error)
}

type globalVTicketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGlobalVTicketServiceClient(cc grpc.ClientConnInterface) GlobalVTicketServiceClient {
	return &globalVTicketServiceClient{cc}
}

func (c *globalVTicketServiceClient) SetTicket(ctx context.Context, in *vtickets.SetGlobalVTicketRequest, opts ...grpc.CallOption) (*vtickets.SetGlobalVTicketResponse, error) {
	out := new(vtickets.SetGlobalVTicketResponse)
	err := c.cc.Invoke(ctx, "/hubspot.vtickets.grpc.GlobalVTicketService/SetTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GlobalVTicketServiceServer is the server API for GlobalVTicketService service.
// All implementations must embed UnimplementedGlobalVTicketServiceServer
// for forward compatibility
type GlobalVTicketServiceServer interface {
	// creates or updates a ticket to start from a specific value
	SetTicket(context.Context, *vtickets.SetGlobalVTicketRequest) (*vtickets.SetGlobalVTicketResponse, error)
	mustEmbedUnimplementedGlobalVTicketServiceServer()
}

// UnimplementedGlobalVTicketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGlobalVTicketServiceServer struct {
}

func (UnimplementedGlobalVTicketServiceServer) SetTicket(context.Context, *vtickets.SetGlobalVTicketRequest) (*vtickets.SetGlobalVTicketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTicket not implemented")
}
func (UnimplementedGlobalVTicketServiceServer) mustEmbedUnimplementedGlobalVTicketServiceServer() {}

// UnsafeGlobalVTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GlobalVTicketServiceServer will
// result in compilation errors.
type UnsafeGlobalVTicketServiceServer interface {
	mustEmbedUnimplementedGlobalVTicketServiceServer()
}

func RegisterGlobalVTicketServiceServer(s grpc.ServiceRegistrar, srv GlobalVTicketServiceServer) {
	s.RegisterService(&GlobalVTicketService_ServiceDesc, srv)
}

func _GlobalVTicketService_SetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vtickets.SetGlobalVTicketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GlobalVTicketServiceServer).SetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubspot.vtickets.grpc.GlobalVTicketService/SetTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GlobalVTicketServiceServer).SetTicket(ctx, req.(*vtickets.SetGlobalVTicketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GlobalVTicketService_ServiceDesc is the grpc.ServiceDesc for GlobalVTicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GlobalVTicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hubspot.vtickets.grpc.GlobalVTicketService",
	HandlerType: (*GlobalVTicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetTicket",
			Handler:    _GlobalVTicketService_SetTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vticketsservice.proto",
}

// HubletVTicketServiceClient is the client API for HubletVTicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubletVTicketServiceClient interface {
	// clears the available tickets, forcing a refresh from the global service on the next request
	ClearTicket(ctx context.Context, in *vtickets.ClearHubletVTicketsRequest, opts ...grpc.CallOption) (*vtickets.ClearHubletVTicketsResponse, error)
}

type hubletVTicketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubletVTicketServiceClient(cc grpc.ClientConnInterface) HubletVTicketServiceClient {
	return &hubletVTicketServiceClient{cc}
}

func (c *hubletVTicketServiceClient) ClearTicket(ctx context.Context, in *vtickets.ClearHubletVTicketsRequest, opts ...grpc.CallOption) (*vtickets.ClearHubletVTicketsResponse, error) {
	out := new(vtickets.ClearHubletVTicketsResponse)
	err := c.cc.Invoke(ctx, "/hubspot.vtickets.grpc.HubletVTicketService/ClearTicket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubletVTicketServiceServer is the server API for HubletVTicketService service.
// All implementations must embed UnimplementedHubletVTicketServiceServer
// for forward compatibility
type HubletVTicketServiceServer interface {
	// clears the available tickets, forcing a refresh from the global service on the next request
	ClearTicket(context.Context, *vtickets.ClearHubletVTicketsRequest) (*vtickets.ClearHubletVTicketsResponse, error)
	mustEmbedUnimplementedHubletVTicketServiceServer()
}

// UnimplementedHubletVTicketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHubletVTicketServiceServer struct {
}

func (UnimplementedHubletVTicketServiceServer) ClearTicket(context.Context, *vtickets.ClearHubletVTicketsRequest) (*vtickets.ClearHubletVTicketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearTicket not implemented")
}
func (UnimplementedHubletVTicketServiceServer) mustEmbedUnimplementedHubletVTicketServiceServer() {}

// UnsafeHubletVTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubletVTicketServiceServer will
// result in compilation errors.
type UnsafeHubletVTicketServiceServer interface {
	mustEmbedUnimplementedHubletVTicketServiceServer()
}

func RegisterHubletVTicketServiceServer(s grpc.ServiceRegistrar, srv HubletVTicketServiceServer) {
	s.RegisterService(&HubletVTicketService_ServiceDesc, srv)
}

func _HubletVTicketService_ClearTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(vtickets.ClearHubletVTicketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubletVTicketServiceServer).ClearTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hubspot.vtickets.grpc.HubletVTicketService/ClearTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubletVTicketServiceServer).ClearTicket(ctx, req.(*vtickets.ClearHubletVTicketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubletVTicketService_ServiceDesc is the grpc.ServiceDesc for HubletVTicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubletVTicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hubspot.vtickets.grpc.HubletVTicketService",
	HandlerType: (*HubletVTicketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClearTicket",
			Handler:    _HubletVTicketService_ClearTicket_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vticketsservice.proto",
}
