buildpack:
  host: git.hubteam.com
  organization: HubSpot
  repository: Blazar-Buildpack-Java
  branch: v2-single-module

env:
  MAVEN_ARGS: -DskipTests
  SET_VERSION_OVERRIDE: 3.0.0-fix-build-SNAPSHOT
  
