enabled: true

buildDeps:
  - hs-build-tools

env:
  GOPATH: '$WORKSPACE/work'

steps:
  - description: Set up custom vitess workspace -- move our clone of the repo into the expected place
    commands:
       - mkdir $WORKSPACE/work/src/github.com/youtube/vitess
       - cp -r $WORKSPACE/vitess/*  $WORKSPACE/work/src/github.com/youtube/vitess/
       - mv /tmp/work $WORKSPACE
       - mkdir -p $GOPATH/bin $GOPATH/pkg

  - description: fetch deps
    commands:
      - |
          export PATH="$GOPATH/bin:$PATH"
          cd $GOPATH/src/github.com/youtube/vitess
          go get -u github.com/golang/lint/golint github.com/golang/mock/mockgen github.com/kardianos/govendor golang.org/x/tools/cmd/goimports honnef.co/go/unused/cmd/unused code.google.com/p/go.tools/cmd/cover
          govendor sync
          cd go/cmd
          go install ./vtgate ./vtctld

  - description: Check it worked
    commands:
      - ls -al $GOPATH/bin

  - description: Package and Upload Deployables
    name: uploadDeployable
    activeByDefault: false
    commands:
      - echo "faking deployable upload"


stepActivation:
  uploadDeployable:
    branches: [hubspot]
